version: "3.7"
volumes:
    traefik-certificates:
networks:
    traefik-public:
      external: true
services:
    traefik:
        image: traefik:v2.0.4
        command:
          - "--log.level=DEBUG"
          - --accesslog
          - "--api.insecure=true"
          - "--metrics.prometheus=true"
          - "--metrics.prometheus.buckets=0.1,0.3,1.2,5.0"
          - "--providers.docker=true"
          - "--providers.docker.swarmmode=true"
          - "--providers.docker.watch"
          - "--providers.docker.exposedbydefault=false"
          - "--providers.docker.network=traefik-public"
          - "--entrypoints.web.address=:80"
          - "--entrypoints.websecure.address=:443"
          - "--certificatesresolvers.letsencryptresolver.acme.httpchallenge=true"
          - "--certificatesresolvers.letsencryptresolver.acme.httpchallenge.entrypoint=web"
          - "--certificatesresolvers.letsencryptresolver.acme.email=${EMAIL?Variable not set}"
          - "--certificatesresolvers.letsencryptresolver.acme.storage=/letsencrypt/acme.json"
        networks:
          - traefik-public
        volumes:
          - traefik-certificates:/letsencrypt
          - /var/run/docker.sock:/var/run/docker.sock
        ports:
          - target: 80
            published: 80
            mode: host
          - target: 443
            published: 443
            mode: host
          - target: 8080
            published: 8080
            protocol: tcp
            mode: ingress
        deploy:
          labels:
            - "traefik.enable=true"
            - "traefik.docker.network=traefik-public"
            - "traefik.http.routers.traefik.rule=Host(`traefik.localhost`)"
            - "traefik.http.services.traefik.loadbalancer.server.port=8080"
            - traefik.http.middlewares.admin-auth.basicauth.users=${USERNAME?Variable not set}:${HASHED_PASSWORD?Variable not set}
            - "traefik.http.routers.traefik.middlewares=admin-auth"
            - "traefik.http.routers.traefik.service=api@internal"
            - "traefik.http.routers.traefik-web.entrypoints=web" 
            - "traefik.http.routers.traefik-secured.rule=Host(`traefik.localhost`)"
            - "traefik.http.routers.traefik-secured.entrypoints=websecure" 
            - "traefik.http.routers.traefik-secured.tls.certresolver=letsencryptresolver" 
          mode: global
          placement:
            constraints:
              - node.role == manager
          update_config:
            parallelism: 1
            delay: 10s
          restart_policy:
            condition: on-failure
