version: "3.7"
networks:
  traefik-public:
    external: true
volumes:
  mongo-data:
    driver: local
  api-data:
    driver: local
  api-logs:
    driver: local
  forest-data:
    driver: local
  forest-logs:
    driver: local
services:
  api:
    image : ${IMAGE?Variable not set}:${VERSION?Variable not set}
    depends_on:
      - mongo
    networks:
      - traefik-public
    volumes:
      - api-data:/app/data
      - api-logs:/app/logs
    deploy:
      mode: replicated
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.api.rule=Host(`staging-api.fatboar.fr`)"
        - "traefik.http.routers.api.service=api"
        - "traefik.http.services.api.loadbalancer.server.port=3000"
        - "traefik.docker.network=traefik-public"
        - "traefik.http.routers.api.entrypoints=web"
        - "traefik.http.routers.api.tls.certresolver=le"
        - "traefik.http.routers.api.entrypoints=websecure"
  forest:
    image: ${Forest_IMAGE?Variable not set}:${VERSION?Variable not set}
    depends_on:
      - mongo
    networks:
      - traefik-public
    volumes:
      - forest-data:/data
      - forest-logs:/logs
    ports:
      - "3002:3000"
    deploy:
      mode: replicated
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.forest.rule=Host(`forest-dev.fatboar.fr`)"
        - "traefik.http.routers.forest.service=forest"
        - "traefik.http.services.forest.loadbalancer.server.port=3000"
        - "traefik.docker.network=traefik-public"
        - "traefik.http.routers.forest.entrypoints=web"
        - "traefik.http.routers.forest.tls.certresolver=le"
        - "traefik.http.routers.forest.entrypoints=websecure"
  mongo:
    image: aashreys/mongo-auth:latest
    volumes:
      - mongo-data:/data/db
    networks:
      - traefik-public
    environment:
      - AUTH=yes
      - MONGODB_ADMIN_USER=fatbordadmin
      - MONGODB_ADMIN_PASS=aze123
      - MONGODB_APPLICATION_DATABASE=fatbord_burger
      - MONGODB_APPLICATION_USER=fatbord
      - MONGODB_APPLICATION_PASS=aze123
    ports:
      - "27017:27017"



