version: "3.7"
networks:
  traefik-public:
    external: true
volumes:
  mongo-data:
    driver: local
  api-data:
    driver: local
  api-logs:
    driver: local
services:
  api:
    image : nexus.fatboar-burger.fr:8123/stagging-node-app:0.0.${VERSION?Variable not set}
    depends_on:
      - mongo
    networks:
      - traefik-public
    volumes:
      - api-data:/srv/data
      - api-logs:/srv/logs
      # code (dev)
      - ./src/common:/srv/app/src/common
      - ./src/microservices/api:/srv/app/src/microservices/api
    deploy:
      mode: replicated
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.api.rule=Host(`staging-api.localhost`)"
        - "traefik.http.routers.api.service=api"
        - "traefik.http.services.api.loadbalancer.server.port=3000"
        - "traefik.docker.network=traefik-public"
        - "traefik.http.routers.api-secured.rule=Host(`staging-api.localhost`)"
        - "traefik.http.routers.api-secured.entrypoints=websecure"
        - "traefik.http.routers.api-secured.tls.certresolver=letsencryptresolver"

  mongo:
    image: aashreys/mongo-auth:latest
    volumes:
      - mongo-data:/data/db
    networks:
      - traefik-public
    environment:
      - AUTH=no
      - MONGODB_ADMIN_USER=fatbordadmin
      - MONGODB_ADMIN_PASS=aze123
      - MONGODB_APPLICATION_DATABASE=fatbord_burger
      - MONGODB_APPLICATION_USER=fatbord
      - MONGODB_APPLICATION_PASS=aze123
    ports:
      - "27017:27017"



