FROM node:14.15.1-alpine3.10

RUN mkdir -p /app

WORKDIR /app

COPY ./package.json /app/
COPY ./yarn.lock /app/
RUN yarn install

COPY ./nodemon.json /app/

EXPOSE 3000
EXPOSE 5000

CMD yarn run forest:debug
